// Generated by CoffeeScript 1.3.3
(function() {
  var Background;

  Background = (function() {

    function Background() {
      this.sourcePictures = [];
      this.extractedBackground = [];
      this.numberOfSourcePictures = 3;
    }

    Background.prototype.get = function() {
      if (this.extractedBackground.length) {
        return this.extractedBackground;
      }
    };

    Background.prototype.init = function(context) {
      var _this = this;
      console.info("initializing Background");
      this.sourcePictures = [];
      this.extractedBackground = [];
      return this.inter = setInterval((function() {
        return _this.getCurrentImageData(context);
      }), 200);
    };

    Background.prototype.getCurrentImageData = function(context) {
      var imagedata;
      console.log("Getting background num" + this.sourcePictures.length);
      imagedata = context.getImageData(0, 0, context.canvas.width, context.canvas.height);
      this.sourcePictures.push(imagedata.data);
      if (this.sourcePictures.length >= this.numberOfSourcePictures) {
        clearInterval(this.inter);
        return this.extractBackgroundFromSourcePictures(context);
      }
    };

    Background.prototype.extractBackgroundFromSourcePictures = function(context) {
      var extractedBackgroundData, i, j, median, sp, _i, _j, _len, _ref, _ref1;
      extractedBackgroundData = [];
      for (i = _i = 0, _ref = this.sourcePictures[0].length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        median = [];
        _ref1 = this.sourcePictures;
        for (j = _j = 0, _len = _ref1.length; _j < _len; j = ++_j) {
          sp = _ref1[j];
          median[j] = sp[i];
        }
        median.sort();
        extractedBackgroundData[i] = median[Math.ceil(this.numberOfSourcePictures / 2)];
      }
      this.extractedBackground = new Uint8Array(extractedBackgroundData);
      return window.g.cm.addTextureToShaders("background", this.extractedBackground);
    };

    return Background;

  })();

  window.Background = Background;

}).call(this);
