// Generated by CoffeeScript 1.3.3
(function() {
  var Background;

  Background = (function() {

    function Background() {
      this.sourcePictures = [];
      this.extractedBackground = [];
      this.numberOfSourcePictures = 7;
      this.tolerance = 20;
    }

    Background.prototype.init = function(context) {
      var _this = this;
      console.info("initializing Background");
      this.sourcePictures = [];
      this.extractedBackground = [];
      return this.inter = setInterval((function() {
        return _this.getCurrentImageData(context);
      }), 1000);
    };

    Background.prototype.getCurrentImageData = function(context) {
      var imagedata;
      console.log("Getting background num" + this.sourcePictures.length);
      imagedata = context.getImageData(0, 0, context.canvas.width, context.canvas.height);
      this.sourcePictures.push(imagedata.data);
      if (this.sourcePictures.length >= this.numberOfSourcePictures) {
        clearInterval(this.inter);
        return this.extractBackgroundFromSourcePictures();
      }
    };

    Background.prototype.extractBackgroundFromSourcePictures = function() {
      var i, j, median, sp, _i, _j, _len, _ref, _ref1, _results;
      _results = [];
      for (i = _i = 0, _ref = this.sourcePictures[0].length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        median = [];
        _ref1 = this.sourcePictures;
        for (j = _j = 0, _len = _ref1.length; _j < _len; j = ++_j) {
          sp = _ref1[j];
          median[j] = sp[i];
        }
        median.sort();
        _results.push(this.extractedBackground[i] = median[Math.ceil(this.numberOfSourcePictures / 2)]);
      }
      return _results;
    };

    Background.prototype.draw = function() {};

    return Background;

  })();

  window.Background = Background;

}).call(this);
