// Generated by CoffeeScript 1.3.3
(function() {
  var Bubble;

  Bubble = (function() {

    function Bubble(id, position) {
      this.id = id;
      position = position;
      this.pixelsIndices = [];
    }

    Bubble.prototype.getIndices = function() {
      return this.pixelsIndices;
    };

    Bubble.prototype.buildPixelsIndices = function(context) {
      var height, i, j, width, _i, _j;
      context.beginPath();
      width = context.canvas.width;
      height = context.canvas.height;
      context.arc(Math.round(width / 3 + (2 % this.id) * width / 6), Math.round(height / 3 + (this.id % 2) * height / 3), 30, 0, Math.PI * 2, true);
      for (i = _i = 0; 0 <= width ? _i < width : _i > width; i = 0 <= width ? ++_i : --_i) {
        for (j = _j = 0; 0 <= height ? _j < height : _j > height; j = 0 <= height ? ++_j : --_j) {
          if (context.isPointInPath(i, j)) {
            this.pixelsIndices.push((j * i) + i);
          }
        }
      }
      return context.closePath();
    };

    Bubble.prototype.draw = function(context, color) {
      var height, width;
      context.strokeStyle = '#F0F';
      context.beginPath();
      width = context.canvas.width;
      height = context.canvas.height;
      context.arc(Math.round(width / 3 + (2 % this.id) * width / 6), Math.round(height / 3 + (this.id % 2) * height / 3), 30, 0, Math.PI * 2, true);
      context.closePath();
      context.stroke();
      if (color !== void 0) {
        context.fillStyle = color;
        return context.fill();
      }
    };

    return Bubble;

  })();

  window.Bubble = Bubble;

}).call(this);
