// Generated by CoffeeScript 1.3.3
(function() {
  var Element;

  Element = (function() {

    function Element(color, sound, bubble) {
      if (color == null) {
        color = new Color;
      }
      if (sound == null) {
        sound = new Sound;
      }
      if (bubble == null) {
        bubble = 0;
      }
      this.color = color;
      this.sound = sound;
      this.bubble = bubble;
    }

    Element.prototype.setBubble = function(obj) {
      if (isNaN(obj)) {
        console.error('set Bubble on NAN : ' + obj);
        return;
      }
      return this.bubble = obj;
    };

    return Element;

  })();

  window.Element = Element;

}).call(this);
