// Generated by CoffeeScript 1.3.3
(function() {
  var Helper;

  Helper = (function() {

    function Helper() {}

    Helper.prototype.clone = function(obj) {
      var flags, key, newInstance;
      if (!(obj != null) || typeof obj !== 'object') {
        return obj;
      }
      if (obj instanceof Date) {
        return new Date(obj.getTime());
      }
      if (obj instanceof RegExp) {
        flags = '';
        if (obj.global != null) {
          flags += 'g';
        }
        if (obj.ignoreCase != null) {
          flags += 'i';
        }
        if (obj.multiline != null) {
          flags += 'm';
        }
        if (obj.sticky != null) {
          flags += 'y';
        }
        return new RegExp(obj.source, flags);
      }
      newInstance = new obj.constructor();
      for (key in obj) {
        newInstance[key] = this.clone(obj[key]);
      }
      return newInstance;
    };

    Helper.prototype.toggleFullScreen = function() {
      if ((document.fullScreenElement && document.fullScreenElement !== null) || (!document.mozFullScreenElement && !document.webkitFullScreenElement)) {
        if (document.documentElement.requestFullScreen) {
          console.log("norm");
          return document.documentElement.requestFullScreen();
        } else if (document.documentElement.mozRequestFullScreen) {
          return document.documentElement.mozRequestFullScreen();
        } else if (document.documentElement.webkitRequestFullScreen) {
          return document.documentElement.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT);
        }
      } else {
        console.log("else");
        if (document.cancelFullScreen) {
          return document.cancelFullScreen();
        } else if (document.mozCancelFullScreen) {
          return document.mozCancelFullScreen();
        } else if (document.webkitCancelFullScreen) {
          return document.webkitCancelFullScreen();
        }
      }
    };

    return Helper;

  })();

  window.Helper = new Helper();

}).call(this);
