// Generated by CoffeeScript 1.3.3
(function() {
  var Sound;

  Sound = (function() {

    function Sound(filename) {
      if (filename == null) {
        filename = "";
      }
      this.filename = filename + ".wav";
      console.info('creating a new sound : ' + this.filename);
      if (filename !== "") {
        this.htmlSound = new Audio("sound/" + this.filename);
      }
    }

    Sound.prototype.play = function() {
      var newHtmlSound;
      if (!this.htmlSound.paused) {
        newHtmlSound = new Audio("sound/" + this.filename);
        newHtmlSound.play();
      }
      return this.htmlSound.play();
    };

    Sound.prototype.stop = function() {
      this.htmlSound.pause();
      return this.htmlSound.currentState = 0;
    };

    Sound.prototype.pause = function() {
      return this.htmlSound.pause();
    };

    return Sound;

  })();

  window.Sound = Sound;

}).call(this);
