// Generated by CoffeeScript 1.3.3
(function() {
  var Visualization;

  Visualization = (function() {

    function Visualization() {
      this.windowWidth = "";
      this.windowHeight = "";
      this.init();
    }

    Visualization.prototype.init = function() {};

    Visualization.prototype.draw = function(context) {};

    return Visualization;

  })();

  window.Visualization = Visualization;

}).call(this);
