// Generated by CoffeeScript 1.3.3
(function() {
  var Webcam;

  Webcam = (function() {

    function Webcam(id) {
      this.video = document.getElementById(id);
      this.checkWebcamCompatibility();
    }

    Webcam.prototype.checkWebcamCompatibility = function() {
      navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia || navigator.msGetUserMedia;
      if (navigator.getUserMedia) {
        console.info("User media is on, let's go !");
        return navigator.getUserMedia({
          video: true,
          audio: false
        }, this.success, this.error);
      } else {
        return console.info("User media is not accessible on this Browser version");
      }
    };

    Webcam.prototype.error = function(error) {
      return console.error('An error on streaming: [CODE ' + error.code + ']');
    };

    Webcam.prototype.success = function(stream) {
      window.URL = window.URL || window.webkitURL || window.mozURL || window.msURL;
      this.stream = stream || window.URL.createObjectURL(stream);
      this.video.src = this.stream;
      return this.video.play();
    };

    return Webcam;

  })();

  window.Webcam = Webcam;

}).call(this);
